const state={rows:[],all:false,test:false,hourly:null,hourlyMessage:'Hodinové měření zatím není zveřejněno.'};
const money=new Intl.NumberFormat('cs-CZ',{style:'currency',currency:'CZK',maximumFractionDigits:0});
const pct=v=>`${Number(v).toLocaleString('cs-CZ',{minimumFractionDigits:2,maximumFractionDigits:2})} %`;
const fmt=(v,type)=>type==='percent'?pct(v):money.format(v);

async function loadProduction(){const r=await fetch(`data/production.json?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json()}
function winner(a,b,prefer){if(a===b)return'both';return prefer==='low'?(a<b?'a':'b'):(a>b?'a':'b')}
function comparisons(row){return{sale:winner(row.ibis.sale_czk,row.golden_gate.sale_czk,'low'),buyback:winner(row.ibis.buyback_czk,row.golden_gate.buyback_czk,'high'),spread:winner(row.ibis.spread_czk,row.golden_gate.spread_czk,'low'),percent:winner(row.ibis.spread_percent,row.golden_gate.spread_percent,'low')}}
function better(which,result){return result==='both'||result===which?'better':''}
function comparisonDate(row){return row?new Date(row.date+'T12:00:00').toLocaleDateString('cs-CZ')+(row.actual_time?' · '+row.actual_time:''):''}
function render(){const rows=state.rows;const latest=rows[0];document.querySelector('#date').textContent=comparisonDate(latest);const cards=document.querySelector('#cards');cards.innerHTML=latest?cardsHtml(latest):'<p>Zatím nejsou zveřejněna žádná měření.</p>';document.querySelector('#hourly-comparison').hidden=state.test;document.querySelector('#hourly-date').textContent=comparisonDate(state.hourly);const hourlyCards=document.querySelector('#hourly-cards');if(state.hourly){hourlyCards.innerHTML=cardsHtml(state.hourly)}else{hourlyCards.replaceChildren();const message=document.createElement('p');message.textContent=state.hourlyMessage;hourlyCards.appendChild(message)}document.querySelector('#history').innerHTML=(state.all?rows:rows.slice(0,30)).map(rowHtml).join('');document.querySelector('#all').hidden=rows.length<=30;document.querySelector('#all').textContent=state.all?'Posledních 30':'Zobrazit vše';document.querySelector('#test-mode').textContent=state.test?'Zpět na produkci':'Testovací data';}
function cardsHtml(r){
  const c=comparisons(r);
  return[['ibis','IBIS','a'],['golden_gate','Golden Gate','b']].map(([key,title,side])=>{
    const v=r[key],other=r[key==='ibis'?'golden_gate':'ibis'];
    const metric=(label,field,result,type='money')=>{
      const delta=v[field]-other[field];
      const advantage=type==='money'&&result===side&&delta!==0
        ?`${delta>0?'+':'−'}${money.format(Math.abs(delta))}`:'';
      return`<div class="metric ${better(side,result)}">${label}<strong>${fmt(v[field],type)}</strong><span class="metric-advantage"${advantage?' title="Rozdíl oproti druhé firmě"':' aria-hidden="true"'}>${advantage}</span></div>`;
    };
    return`<article class="card ${key==='ibis'?'ibis':'gg'}"><h3>${title}</h3><div class="metrics">${metric('Prodej','sale_czk',c.sale)}${metric('Výkup','buyback_czk',c.buyback)}${metric('Spread','spread_czk',c.spread)}${metric('Spread','spread_percent',c.percent,'percent')}</div></article>`;
  }).join('');
}
function rowHtml(r){const c=comparisons(r),cell=(v,side,result,type='money')=>`<td class="${better(side,result)}">${fmt(v,type)}</td>`,repair=r.corrected?'ano':'—';return`<tr class="day-prices"><td class="day" rowspan="2">${new Date(`${r.date}T12:00:00`).toLocaleDateString('cs-CZ')}</td>${cell(r.ibis.sale_czk,'a',c.sale)}${cell(r.ibis.buyback_czk,'a',c.buyback)}${cell(r.golden_gate.sale_czk,'b',c.sale)}${cell(r.golden_gate.buyback_czk,'b',c.buyback)}<td class="secondary" rowspan="2">${r.scheduled_time||'18:20'}</td><td class="secondary" rowspan="2">${r.actual_time||'—'}</td><td class="secondary" rowspan="2">${repair}</td></tr><tr class="day-spreads">${cell(r.ibis.spread_czk,'a',c.spread)}${cell(r.ibis.spread_percent,'a',c.percent,'percent')}${cell(r.golden_gate.spread_czk,'b',c.spread)}${cell(r.golden_gate.spread_percent,'b',c.percent,'percent')}</tr>`}
async function unlock(password){const r=await fetch(`data/test.enc?t=${Date.now()}`,{cache:'no-store'}),p=await r.json(),dec=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0)),enc=new TextEncoder(),keyMaterial=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']),key=await crypto.subtle.deriveKey({name:'PBKDF2',salt:dec(p.salt),iterations:p.iterations,hash:'SHA-256'},keyMaterial,{name:'AES-GCM',length:256},false,['decrypt']),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:dec(p.iv)},key,dec(p.ciphertext));return JSON.parse(new TextDecoder().decode(plain))}
function csv(){const head=['datum','ibis_prodej','ibis_vykup','ibis_spread_kc','ibis_spread_pct','gg_prodej','gg_vykup','gg_spread_kc','gg_spread_pct'];const body=state.rows.map(r=>[r.date,r.ibis.sale_czk,r.ibis.buyback_czk,r.ibis.spread_czk,r.ibis.spread_percent,r.golden_gate.sale_czk,r.golden_gate.buyback_czk,r.golden_gate.spread_czk,r.golden_gate.spread_percent]);const blob=new Blob([[head,...body].map(x=>x.join(';')).join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`porovnani-cen-${state.test?'test':'produkce'}.csv`;a.click();URL.revokeObjectURL(a.href)}
document.querySelector('#theme').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('theme',document.body.classList.contains('dark')?'dark':'light')};if(localStorage.getItem('theme')==='dark'||(!localStorage.getItem('theme')&&matchMedia('(prefers-color-scheme:dark)').matches))document.body.classList.add('dark');
document.querySelector('#all').onclick=()=>{state.all=!state.all;render()};document.querySelector('#csv').onclick=csv;document.querySelector('#test-mode').onclick=()=>{if(state.test){location.reload()}else document.querySelector('#password-dialog').showModal()};document.querySelector('#cancel-password').onclick=()=>{document.querySelector('#password').value='';document.querySelector('#password-error').textContent='';document.querySelector('#password-dialog').close()};document.querySelector('#unlock').onclick=async e=>{e.preventDefault();try{state.rows=await unlock(document.querySelector('#password').value);state.test=true;document.querySelector('#password').value='';document.querySelector('#password-dialog').close();document.querySelector('#notice').hidden=false;document.querySelector('#notice').textContent='Zobrazená data jsou testovací a nejsou součástí produkční historie.';render()}catch{document.querySelector('#password-error').textContent='Nesprávné heslo nebo neplatná testovací data.'}};
loadProduction().then(rows=>{state.rows=rows.sort((a,b)=>b.date.localeCompare(a.date));render()}).catch(e=>{document.querySelector('#notice').hidden=false;document.querySelector('#notice').textContent=`Data se nepodařilo načíst: ${e.message}`});
async function loadHourly(){try{const response=await fetch(`data/latest.json?t=${Date.now()}`,{cache:'no-store'});if(response.status===404){state.hourlyMessage='Hodinové měření zatím není zveřejněno.'}else{if(!response.ok)throw Error(`HTTP ${response.status}`);state.hourly=await response.json()}}catch{state.hourlyMessage='Aktuální porovnání se nepodařilo načíst. Zkuste stránku obnovit.'}render()}
loadHourly();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
